### ISSUE TITLE
breadcrumbs for navigations

### ISSUE THREAD

**Issue by detaybey** [deepnetworkgmbh/joseki#107]
or should we remove back button on history page?

**Comment by yufufi** [comment]
To me `back` implies going back to where I came from which is a bit of tricky concept. And for that the browser `back` button is sufficient. However, it's not a bad idea to have a button to go to a less specific page.

For example if you're in the details page of an image scan (and you get there by clicking on a link someone sent you) it might be nice to have a link to the main scan that it is part of.

Case in point, let's say I sent you [this](http://localhost:8080/image-detail/mcr.microsoft.com%2Foss%2Fkubernetes%2Fhyperkube%3Av1.16.7_f0.0.1/2020-03-22) link. How do you go to [this](http://localhost:8080/component-detail/%2fk8s%2f8fc1b601-d5a2-466d-8236-c747c1dc02a2/2020-03-22) page from there?

Maybe we should build a navigation stack on the top that users can navigate from more specific to more generic? In the case above it _may_ look like this:

[2020-03-22 Scans](http://localhost:8080/overview/2020-03-22) > [Kubernetes: dn-common](http://localhost:8080/component-detail/%252fk8s%252f8fc1b601-d5a2-466d-8236-c747c1dc02a2/2020-03-22) > [kube-proxy image](http://localhost:8080/component-detail/%2fk8s%2f8fc1b601-d5a2-466d-8236-c747c1dc02a2/2020-03-22)

**Comment by detaybey** [comment]
looks like this
<img width="341" alt="Screen Shot 2020-03-26 at 16 40 35" src="https://user-images.githubusercontent.com/784409/77653254-8c62be80-6f80-11ea-8ef3-4120cfd96512.png">
