### ISSUE TITLE
Implement a page that shows all results from all types of objects

### ISSUE THREAD

**Issue by yufufi** [deepnetworkgmbh/joseki#152]
This page should be able to show issues from all types of scanners together.
It should support multiple filtering options to narrow down to specific components, specific type of issues etc.

It will also be used on the scan landing page as a sub component.

**Comment by detaybey** [comment]
There has to be a correction here, we already unified `all types of objects` into a single object and we named it an [InfrastructureComponent](https://github.com/deepnetworkgmbh/joseki/blob/master/src/backend/joseki.be/webapp/Models/InfrastructureComponent.cs) , this page will be displaying a super-set of InfrastructureComponent and it's corresponding scan results on a specific date.

It will support a list display with pagination, and filtering of several properties. We are discussing with Igor about if the sorting/filtering should be done on client side or server side and other details.
