### ISSUE TITLE
Display check-result remediation/recommendation option

### ISSUE THREAD

**Issue by detaybey** [deepnetworkgmbh/joseki#212]
in the current scan results, we're displaying the problem but not using the recommendation field in the [metadata](https://www.powershellgallery.com/packages/AzSK/3.10.0/Content/Framework%5CConfigurations%5CSVT%5CServices%5CStorage.json).

for example, recommendation for "ControlID": "Azure_Storage_Audit_AuthN_Requests", is
`"Recommendation": "Run command 'Set-AzureStorageServiceLoggingProperty -ServiceType '<Blob/Queue/Table>' -LoggingOperations 'All' -Context '<StorageContext>' -RetentionDays '365' -PassThru'. Run 'Get-Help Set-AzureStorageServiceLoggingProperty -full' for more help. Set-AzureStorageServiceMetricsProperty -MetricsType 'Hour' -ServiceType '<Blob/Queue/Table/File>' -Context '<StorageContext>' -MetricsLevel 'ServiceAndApi' -RetentionDays '365' -PassThru. Run 'Get-Help Set-AzureStorageServiceMetricsProperty -full' for more help.",`

**Comment by v1r7u** [comment]
I think, adding the remediation action or recommendation to the same interface might not work as we want:
- imagine an Azure scan details page, where each check is accompanied with 1-10 sentences of additional text.
- I guess, in some cases, users would want to copy-paste this data, so showing it in tooltip would not work either.

As an alternative approach, we can create a dedicated page for each check type, where we are not limited that much. In a way similar to image scan details.

**Comment by savas-guven** [comment]
I would also be OK with a separate page -- please make these pages URL accessible directly as well.

**Comment by v1r7u** [comment]
At the moment, there are three types of checks in our system:
1. docker-image scans by trivy
2. azure infrastructure scans by azsk
3. kubernetes scans by polaris

The thing is, that all three of them requires a different approach:
- azsk gives a `remediation` option as a part of the scan result, so we can parse automatically (what is done already)
- polaris does not give a lot of details in the scan result, but it has extensive documentation as part of their dashboard: https://github.com/FairwindsOps/polaris/tree/master/docs/check-documentation
- trivy suggests only if the package could be packaged or not (which is, indeed, enough)

Here is my proposal:
1. Each `check` (or `control`) should have an associated page, which describes the item in detail. This description should include the remediation/recommendation text. Later on, we can extend this page with more details (for example, all the components, that failed/succeeded the check)
2. Preinsert data into `Knowledgebase` table with polaris check descriptions. Use `checks.{CheckId}` as `ItemId`.
3. Create `checks.default_template` `Knowledgebase` item, which could be used as fall back option. It could have content like
    Check id | Recommendation
    --- | --- 
    ${check_id} | ${check_recommendation}
4. When check details page is requested, `backend` tries to find corresponding `Knowledgebase` item, if it does not exist, it loads a default one and substitutes placeholders with data from `CheckEntity`
5. I think, Image scan details page (which is also _a check description_ in a way) could be left as is

As an addition, I'd prefer to use markdown as the format of `Knowledgebase` content and render it as HTML on user-side. If this is possible, it allows storing reacher content  in the database, which could be useful in other places too

**Comment by detaybey** [comment]
We decided to move knowledgebase information to individual md files, this way we will be able to maintain/update the corresponding documentation easier. This would also help us serve detailed information on checks, using markdown documents related to the check id's. 

This task is splitted into three parts 
- [ ] Move Knowledgebase files into md formatted text files.
- [ ] Create an endpoint (both FE/BE) for serving a document related to a check.
- [ ] Link related scan result pages to this endpoint using _check id_.

**Comment by detaybey** [comment]
- created a fallback template for any document that does not have an md file. the KnowledgebaseItemHandler now checks if the file exists, and serves a document on the fly by injecting Description and Remediation information into template.
- removed azsk files as the fallback template can serve the current check information.
