### ISSUE TITLE
[Attestation] Add targets ownership

### ISSUE THREAD

**Issue by v1r7u** [deepnetworkgmbh/joseki#217]
Joseki should support resource ownership to help teams collaborate on issues.

Ownership should be hierarchical:
- deployment/namespace/k8s-cluster; azure-component/resource-group/subscription
- at each hierarchy level could be used another owner
- the most specific owner takes precedence of the higher one
- if there is no owner for a given component - value is taken from the next hierarchy level item

`Frontend` displays ownership field next to resources at infrastructure-component pages.
`Backend` tries to parse ownership value from tag `owner`. The tag should be parsed from both: azure-infrastructure and kubernetes metadata. The latest owner value should overwrite the previous one.

(Optional): add filter by the owner to the table-results and infrastructure-component page.

At the moment, these features are **out of context**:
- editing ownership values
- default ownership
- support different owners for the same component over the time

### Proposal for the Ownership data model

Column Name | Value
--- | ---
ComponentId | {componentId} 
Owner | {owner_tag_content}

Where `componentId` has format `subscription/{id}/resource_group/{rg_name}/{object_type}/{object_name}` or `k8s/{cluster_id}/namespace/{ns_name}/{object_type}/{object_name}`. If componentId does not include all available subsections - ownership covers all the components, that starts with it. For example:
- `subscription/{id}/resource_group/{rg_name}` covers all the resources in the given subscription and resource group
- `k8s/{cluster_id}` covers all the k8s objects in a given cluster

You can consider absent data as a wildcard symbol `*`.

**Comment by detaybey** [comment]
- [x] Created an Ownership entity & table, added migration for it.
- [x] Started working on an AuditPostProcessor to extract the ownership data from an Audit.
- [ ] Will write a function (maybe an MSSQL function, don't know yet) to return the recent Owner for the requested Resource path.
