### ISSUE TITLE
[area/frontend] Font sizes can be increased

### ISSUE THREAD

**Issue by emrahkaya** [deepnetworkgmbh/joseki#234]
The fonts of pie-chart and bar-graphs are a bit small. As they're blended into colored backgrounds with white fonts, it feels smaller and hard to read (especially for the blueish and orange background).
![image](https://user-images.githubusercontent.com/546687/81329877-dd012780-90a7-11ea-8399-92f3e51f2573.png)

**Comment by emrahkaya** [comment]
I've discovered only owner/contributors can add labels to an issue. And the community seems to find a way to suggest labels by adding it to the issue title 🤷 : https://stackoverflow.com/a/13829505/4940507

**Comment by detaybey** [comment]
small font sizes increased where possible.
status bar component styling changed.
pie chart fonts increased.
color adjustments for ScanResult and Score tags.
<img width="1151" alt="Screen Shot 2020-05-29 at 14 07 37" src="https://user-images.githubusercontent.com/784409/83253536-cd13c980-a1b5-11ea-869f-415263dedab1.png">

<img width="1183" alt="Screen Shot 2020-05-29 at 13 56 28" src="https://user-images.githubusercontent.com/784409/83252704-6510b380-a1b4-11ea-8b8f-b65b33c4524b.png">
<img width="415" alt="Screen Shot 2020-05-29 at 13 56 44" src="https://user-images.githubusercontent.com/784409/83252705-66da7700-a1b4-11ea-9590-c32f8c19c503.png">
