### ISSUE TITLE
[area/frontend] The Scan History page will be better with accompanying graph

### ISSUE THREAD

**Issue by emrahkaya** [deepnetworkgmbh/joseki#235]
When I open the homepage, I can see the graph of last 5 scans:
![image](https://user-images.githubusercontent.com/546687/81330750-387fe500-90a9-11ea-89ef-c3d247084995.png)

However, when I select "See Scan History" and hit the "Scan History" page, I can only see the table. 

A similar graph that shows a wider range of history (the ones in the table) might look nice and be helpful for visualizing the rate of change better.

**Comment by v1r7u** [comment]
I find it reasonable.

@detaybey what do you think about the proposal?

**Comment by detaybey** [comment]
we can use a graph at history page, it makes sense.

**Comment by detaybey** [comment]
![Screen Shot 2020-05-21 at 15 36 25](https://user-images.githubusercontent.com/784409/82559783-db8c3080-9b78-11ea-9b9e-16be2a7d5a0b.png)
