### ISSUE TITLE
Verify backend query for landing page

### ISSUE THREAD

**Issue by yufufi** [deepnetworkgmbh/joseki#28]
Please create issues if the query doesn’t satisfy the UI needs.

**Comment by detaybey** [comment]
- [ ] overallScoreHistory must have dates of scans

**Comment by v1r7u** [comment]
![image](https://user-images.githubusercontent.com/1583399/73357756-6204c580-429d-11ea-8029-cd1b00d67724.png)
I expected that array always contains data for the last 30 days.
If date is added to each item, the response has enormous amount of duplicated values

**Comment by v1r7u** [comment]
Let's continue the chat in PR itself
