### ISSUE TITLE
Design third-party deployment

### ISSUE THREAD

**Issue by savas-guven** [deepnetworkgmbh/joseki#55]
The initial deployment includes: infrastructure, service-principals, applications.

- [x] design proposal
- [x] implement scripts/templates
- [ ] document the process

**Comment by yufufi** [comment]
The goal of this item is to simply document and script replicating current deployment model. That is, deploying `joseki` to a Azure Kubernetes Cluster.

**Comment by yufufi** [comment]
In the future we'll also consider other deployment mechanism such as deploying to containers directly. @v1r7u please create necessary tasks.
