### ISSUE TITLE
Joseki authentication

### ISSUE THREAD

**Issue by v1r7u** [deepnetworkgmbh/joseki#89]
The application should have an option to be exposed to the wild internet. Thus:
- Only trusted users should be able to access the website;
- API should respond 401 to untrusted entities;

At the beginning, Joseki should support only basic authentication mode at reverse-proxy layer

**Comment by yufufi** [comment]
Very most likely this is not needed as we're gonna go with some kind of ingress controller. This will put both BE & FE behind the same endpoint. And this endpoint will support some kind of authentication (+ HTTPS). 

See #147 for more details of exposing the service publicly.
